require('dotenv').config();
const pool = require('../config/db');
const { htmlToText } = require('../services/htmlToText');
const { logger } = require('../config/logger');

const PAGES = [
  {
    slug: 'terms',
    title: 'Terms of Use',
    type: 'policy',
    meta_description: 'Terms and conditions for using the E-Nyagasambu marketplace.',
    content: `
<h2>1. Acceptance of Terms</h2>
<p>By accessing or using E-Nyagasambu ("the Platform"), you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, please do not use the Platform.</p>

<h2>2. Using the Platform</h2>
<p>You may use the Platform to browse listings, contact sellers, post listings, and make payments. You agree to provide accurate information when creating an account, posting listings, or completing transactions, and to keep your account credentials confidential.</p>

<h2>3. Listing Rules</h2>
<ul>
  <li>Posting a listing costs <strong>400 coins</strong> and requires a valid payment.</li>
  <li>Listings must be truthful and must not mislead buyers. Prohibited content includes spam, illegal goods, fraudulent offers, and misleading descriptions.</li>
  <li>We reserve the right to disable or remove listings that violate these rules.</li>
</ul>

<h2>4. Payments and Refunds</h2>
<p>Coins can be purchased via MTN MoMo or Airtel Money. Once a listing is published or a contact is revealed, the associated coins are consumed and are generally non-refundable. Contact access costs <strong>300 RWF</strong> per seller reveal.</p>

<h2>5. Prohibited Conduct</h2>
<ul>
  <li>Do not attempt to bypass or interfere with the Platform's security or payment systems.</li>
  <li>Do not use the Platform to defraud other users.</li>
  <li>Do not scrape, copy, or reuse content without permission.</li>
</ul>

<h2>6. Limitation of Liability</h2>
<p>E-Nyagasambu acts as an intermediary marketplace and is not a party to transactions between buyers and sellers. To the maximum extent permitted by law, we are not liable for disputes between users or for indirect, incidental, or consequential damages.</p>

<h2>7. Changes to These Terms</h2>
<p>We may update these Terms of Use from time to time. Continued use of the Platform after changes are posted constitutes acceptance of the revised terms.</p>

<h2>8. Contact</h2>
<p>Questions about these terms can be sent to <strong>Enyagasambu@gmail.com</strong>.</p>
`,
  },
  {
    slug: 'privacy',
    title: 'Privacy Policy',
    type: 'policy',
    meta_description: 'How E-Nyagasambu collects, uses, and protects your personal information.',
    content: `
<h2>1. Information We Collect</h2>
<p>We collect information you provide directly, such as your name, phone number, email address, and business details, as well as information generated by your use of the Platform, including listings, payments, and support requests.</p>

<h2>2. How We Use Your Information</h2>
<ul>
  <li>To operate and improve the Platform.</li>
  <li>To process payments and manage your coin balance.</li>
  <li>To connect buyers and sellers and to provide seller contact details after a valid reveal.</li>
  <li>To respond to support requests and enforce our rules.</li>
</ul>

<h2>3. Contact Information Disclosure</h2>
<p>Seller phone numbers are only revealed to a buyer after the buyer completes a verified contact-access payment. We never publish your personal contact details publicly beyond what you choose to share in your listings or business profile.</p>

<h2>4. Data Security</h2>
<p>We use appropriate technical and organizational measures to protect your data, including encryption of sensitive records and access controls. However, no method of transmission over the internet is fully secure.</p>

<h2>5. Data Retention</h2>
<p>We retain your data for as long as your account is active or as needed to provide the service, comply with legal obligations, and resolve disputes.</p>

<h2>6. Your Rights</h2>
<p>You may update your personal information through your account settings or by contacting us. You may also request deletion of your account and associated data.</p>

<h2>7. Contact</h2>
<p>For privacy inquiries, contact <strong>Enyagasambu@gmail.com</strong>.</p>
`,
  },
  {
    slug: 'faq',
    title: 'Frequently Asked Questions',
    type: 'faq',
    meta_description: 'Common questions about listing, payments, and seller contact access.',
    content: `
<h2>How do I create a listing?</h2>
<p>Click "Posting" in the top bar, fill in the details about your product or service, and pay <strong>400 coins</strong> to publish it.</p>

<h2>How do I buy coins?</h2>
<p>Go to <a href="/coins">Coins &amp; Wallet</a> from your account menu, select a package, and pay via MTN MoMo or Airtel Money.</p>

<h2>How do I contact a seller?</h2>
<p>Open the listing you are interested in, click <strong>Get Seller Contact</strong>, verify with OTP, and pay <strong>300 RWF</strong> to reveal the seller's phone number.</p>

<h2>What happens when a listing is reported?</h2>
<p>Reported listings are reviewed by our moderation team. If a listing violates our rules it may be disabled while it is reviewed.</p>

<h2>How do I become an ambassador?</h2>
<p>Register as an ambassador via the Ambassador Registration link, then pay for your certificate to start referring and earning.</p>

<h2>How do I become a supplier?</h2>
<p>Create an account and register as a supplier to showcase your business in the public supplier directory. Businesses shown as verified have completed our verification process.</p>

<h2>Why can't I access seller contacts?</h2>
<p>Contact access requires an OTP verification and a valid payment. If you have exceeded the allowed OTP attempts, wait for the lockout period to expire and try again.</p>

<h2>Still need help?</h2>
<p>Visit the <a href="/support">Support page</a> and submit a request, or call us directly during business hours.</p>
`,
  },
];

async function run() {
  console.log('Seeding legal pages...');
  const [[admin]] = await pool.query(
    "SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1"
  );
  const authorId = admin ? admin.id : null;

  for (const page of PAGES) {
    const content = htmlToText(page.content);
    const [existing] = await pool.query('SELECT id FROM content_pages WHERE slug = ?', [page.slug]);
    if (existing.length > 0) {
      await pool.query(
        `UPDATE content_pages SET title = ?, type = ?, content = ?, status = 'published',
         meta_description = ?, updated_by = ? WHERE slug = ?`,
        [page.title, page.type, content, page.meta_description, authorId, page.slug]
      );
      console.log(`  [updated] ${page.slug}`);
    } else {
      await pool.query(
        `INSERT INTO content_pages (title, slug, type, content, status, meta_description, created_by, updated_by)
         VALUES (?, ?, ?, ?, 'published', ?, ?, ?)`,
        [page.title, page.slug, page.type, content, page.meta_description, authorId, authorId]
      );
      console.log(`  [created] ${page.slug}`);
    }
  }

  console.log('Legal pages seeded.');
  process.exit(0);
}

run().catch((err) => {
  logger.error('Seed failed:', err.message);
  process.exit(1);
});
